<?php

namespace AppBundle\Repository;

/**
 * EvaluationAnswerImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationAnswerImageRepository extends \Doctrine\ORM\EntityRepository
{
}
