<?php

namespace AppBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSubcategoriesDone($id){
        $qb = $this->createQueryBuilder('e');
        $qb
            ->select('e.subcategoriesDone')
            ->andWhere('e.id = :id')
            ->setParameter(':id', $id);
        ;

        return $qb->getQuery()->getOneOrNullResult();

    }

}
