<?php

namespace AppBundle\Repository;

/**
 * EvaluationAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationAnswersRepository extends \Doctrine\ORM\EntityRepository
{
}
