<?php

namespace AppBundle\Repository;

/**
 * EvaluationAnswerPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationAnswerPhotosRepository extends \Doctrine\ORM\EntityRepository
{
}
