<?php

namespace AppBundle\Repository;

/**
 * QuestionSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
