imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    photos_directory: '%kernel.project_dir%/web/uploads/evaluations'

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# EasyAdmin Configuration
easy_admin:
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
    site_name: 'EatSalad'
    design:
        brand_color: '#76B728'
        menu:
            - { entity: 'Evaluation', label: 'Évaluation', icon: 'check-circle', default: true }
            - label: 'Questions'
              icon: 'tasks'
              children:
                  - { entity: 'Category', label: 'Catégories', icon: 'folder' }
                  - { entity: 'SubCategory', label: 'Sous-Catégories', icon: 'folder-open' }
                  - { entity: 'Question', label: 'Questions', icon: 'question' }
            - { entity: 'Answer', label: 'Réponses', icon: 'comment' }
            - { entity: 'City', label: 'Villes', icon: 'map-marker' }
            - { entity: 'Restaurant', label: 'Restaurants', icon: 'cutlery' }
        assets:
            favicon: '/assets/backend/favicon.png'
    entities:
        Answer:
            class: AppBundle\Entity\Answer
        Question:
            class: AppBundle\Entity\Question
            edit:
                fields:
                    - { property: 'position', icon: 'position', help: 'Position de la question dans la sous-catégorie' }
                    - { property: 'question', icon: 'question' }
                    - { property: 'subCategory', icon: 'question' }
        Category:
            class: AppBundle\Entity\Category
        SubCategory:
            class: AppBundle\Entity\SubCategory
            edit:
                fields:
                    - { property: 'name'}
                    - { property: 'category'}
                    - { property: 'questions', type: 'entity', type_options: { class: 'AppBundle\Entity\Question', multiple: true } }
        Evaluation:
            class: AppBundle\Entity\Evaluation
            list:
                fields: ['id', 'restaurant', { property: 'score', label: 'Score' }, { property: 'date', type: 'date', format: 'd/m/Y' }, { property: 'controllerName', label: 'Controlleur' }, { property: 'accepted', label: 'Acceptation par le franchisé', type: 'boolean' }]
                actions:
                    - { label: '', name: 'report_download', icon: 'file-text-o', type: 'route' }
        Restaurant:
            class: AppBundle\Entity\Restaurant
        City:
            class: AppBundle\Entity\City

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false

# FOSRest Configuration
fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/rest', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/admin', stop: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true

# Stof\DoctrineExtensionsBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sortable: true

knp_snappy:
    pdf:
        enabled:    true
        binary:     /home/bmagneovix/wkhtmltox/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []